package kr.valor.juggernaut.data.session.mapper.delegate.routinesprovider.amrap

import kr.valor.juggernaut.common.Phase
import org.hamcrest.CoreMatchers.`is`
import org.hamcrest.MatcherAssert.assertThat

fun AMRAPRoutinesProviderDelegate.`validate routines that were generated by delegate`(table: PhaseOverallRoutineIntensityTable, action: (Double) -> Double) {
    Phase.values().forEach { phase ->
        val tm = 60.0
        val sessionRoutines = provideRoutines(phase, tm)
        val routines = sessionRoutines.warmupRoutines + sessionRoutines.amrapRoutine

        routines.forEachIndexed { index, (weights, reps) ->
            val routineIntensityTable = table[phase]!!
            val (repetitions, intensity) = routineIntensityTable[index]

            assertThat(weights, `is`(action(tm * intensity)))
            assertThat(reps, `is`(repetitions))
        }
    }
}