package kr.valor.juggernaut.data.session.mapper.delegate.routinesprovider.amrap

import kr.valor.juggernaut.data.session.mapper.delegate.property.DefaultPropertyMediateDelegate
import org.junit.Before
import org.junit.Test

class BasicAccumulationRoutinesProviderDelegateTest {

    private lateinit var targetProviderDelegate: AMRAPRoutinesProviderDelegate
    private lateinit var table: PhaseOverallRoutineIntensityTable
    private val action = DefaultPropertyMediateDelegate::mediate

    @Before
    fun `init`() {
        targetProviderDelegate =
            BasicAccumulationRoutinesProviderDelegate(
                DefaultPropertyMediateDelegate
            )
        table = BasicAccumulationRoutinesProviderDelegate
            .ACCUMULATION_CYCLE_OVERALL_ROUTINE_INTENSITY_TABLE
    }

    @Test
    fun `BasicAccumulationRoutinesProviderDelegate generates routines as expected`() {
        targetProviderDelegate.`validate routines that were generated by delegate`(table, action)
    }
}