package kr.valor.juggernaut.data.session.mapper.delegate.routinesprovider.amrap

import kr.valor.juggernaut.data.session.mapper.delegate.property.DefaultPropertyMediateDelegate
import org.junit.Before
import org.junit.Test

class BasicRealizationRoutinesProviderDelegateTest {

    private lateinit var targetProviderDelegate: AMRAPRoutinesProviderDelegate
    private lateinit var table: PhaseOverallRoutineIntensityTable
    private val action = DefaultPropertyMediateDelegate::mediate

    @Before
    fun `init`() {
        targetProviderDelegate =
            BasicRealizationRoutinesProviderDelegate(
                DefaultPropertyMediateDelegate
            )
        table = BasicRealizationRoutinesProviderDelegate
            .overallRoutineIntensityTable
    }

    @Test
    fun `BasicRealizationRoutinesProviderDelegate generates routines as expected`() {
        targetProviderDelegate.`validate routines that were generated by delegate`(table, action)
    }
}