package kr.valor.juggernaut.data.session.mapper.delegate.routine.basic.deload

import kr.valor.juggernaut.data.session.mapper.delegate.property.DefaultPropertyMediateDelegate
import kr.valor.juggernaut.data.session.mapper.delegate.routine.`validate routines that were generated by delegate`
import kr.valor.juggernaut.data.session.mapper.delegate.routine.basic.PhaseEntireRoutineIntensityTable
import org.junit.Before
import org.junit.Test


class DeloadRoutinesProviderDelegateTest {

    private lateinit var targetProviderDelegate: DeloadRoutinesProviderDelegate
    private lateinit var table: PhaseEntireRoutineIntensityTable
    private val action = DefaultPropertyMediateDelegate::mediate

    @Before
    fun `init`() {
        targetProviderDelegate =
            DeloadRoutinesProviderDelegate(
                DefaultPropertyMediateDelegate
            )
        table = DeloadRoutinesProviderDelegate
            .routineIntensityMap
    }

    @Test
    fun `BasicDeloadRoutinesProviderDelegate generates routines as expected`() {
        targetProviderDelegate.`validate routines that were generated by delegate`(table, action)
    }

}