package kr.valor.juggernaut.common

const val PHASE_REP10_WARMUP_ROUTINE_NUMBER = 4
const val PHASE_REP8_WARMUP_ROUTINE_NUMBER = 4
const val PHASE_REP5_WARMUP_ROUTINE_NUMBER = 5
const val PHASE_REP3_WARMUP_ROUTINE_NUMBER = 6

const val ACCUMULATION_CYCLE_PHASE_REP10_INTENSITY = 0.6
const val ACCUMULATION_CYCLE_PHASE_REP10_REPETITIONS = 10
const val ACCUMULATION_CYCLE_PHASE_REP10_SETS = 4

const val ACCUMULATION_CYCLE_PHASE_REP8_INTENSITY = 0.65
const val ACCUMULATION_CYCLE_PHASE_REP8_REPETITIONS = 8
const val ACCUMULATION_CYCLE_PHASE_REP8_SETS = 4

const val ACCUMULATION_CYCLE_PHASE_REP5_INTENSITY = 0.7
const val ACCUMULATION_CYCLE_PHASE_REP5_REPETITIONS = 5
const val ACCUMULATION_CYCLE_PHASE_REP5_SETS = 5

const val ACCUMULATION_CYCLE_PHASE_REP3_INTENSITY = 0.75
const val ACCUMULATION_CYCLE_PHASE_REP3_REPETITIONS = 3
const val ACCUMULATION_CYCLE_PHASE_REP3_SETS = 6


const val INTENSIFICATION_CYCLE_PHASE_REP10_WARMUP_SET1_INTENSITY = 0.55
const val INTENSIFICATION_CYCLE_PHASE_REP10_WARMUP_SET2_INTENSITY = 0.625
const val INTENSIFICATION_CYCLE_PHASE_REP10_MAIN_SET_INTENSITY = 0.675
const val INTENSIFICATION_CYCLE_PHASE_REP10_WARMUP_OVERALL_REPETITIONS = 5
const val INTENSIFICATION_CYCLE_PHASE_REP10_MAIN_OVERALL_REPETITIONS = 10

const val INTENSIFICATION_CYCLE_PHASE_REP8_WARMUP_SET1_INTENSITY = 0.6
const val INTENSIFICATION_CYCLE_PHASE_REP8_WARMUP_SET2_INTENSITY = 0.675
const val INTENSIFICATION_CYCLE_PHASE_REP8_MAIN_SET_INTENSITY = 0.725
const val INTENSIFICATION_CYCLE_PHASE_REP8_WARMUP_OVERALL_REPETITIONS = 3
const val INTENSIFICATION_CYCLE_PHASE_REP8_MAIN_OVERALL_REPETITIONS = 8

const val INTENSIFICATION_CYCLE_PHASE_REP5_WARMUP_SET1_INTENSITY = 0.65
const val INTENSIFICATION_CYCLE_PHASE_REP5_WARMUP_SET2_INTENSITY = 0.725
const val INTENSIFICATION_CYCLE_PHASE_REP5_MAIN_SET_INTENSITY = 0.775
const val INTENSIFICATION_CYCLE_PHASE_REP5_WARMUP_OVERALL_REPETITIONS = 2
const val INTENSIFICATION_CYCLE_PHASE_REP5_MAIN_OVERALL_REPETITIONS = 5

const val INTENSIFICATION_CYCLE_PHASE_REP3_WARMUP_SET1_INTENSITY = 0.7
const val INTENSIFICATION_CYCLE_PHASE_REP3_WARMUP_SET2_INTENSITY = 0.775
const val INTENSIFICATION_CYCLE_PHASE_REP3_MAIN_SET_INTENSITY = 0.825
const val INTENSIFICATION_CYCLE_PHASE_REP3_WARMUP_OVERALL_REPETITIONS = 1
const val INTENSIFICATION_CYCLE_PHASE_REP3_MAIN_OVERALL_REPETITIONS = 3


const val REALIZATION_CYCLE_PHASE_REP10_WARMUP_SET1_INTENSITY = 0.5
const val REALIZATION_CYCLE_PHASE_REP10_WARMUP_SET1_REPETITIONS = 5
const val REALIZATION_CYCLE_PHASE_REP10_WARMUP_SET2_INTENSITY = 0.6
const val REALIZATION_CYCLE_PHASE_REP10_WARMUP_SET2_REPETITIONS = 3
const val REALIZATION_CYCLE_PHASE_REP10_WARMUP_SET3_INTENSITY = 0.7
const val REALIZATION_CYCLE_PHASE_REP10_WARMUP_SET3_REPETITIONS = 1
const val REALIZATION_CYCLE_PHASE_REP10_MAIN_SET_INTENSITY = 0.75
const val REALIZATION_CYCLE_PHASE_REP10_MAIN_SET_REPETITIONS_CRITERION = 10

const val REALIZATION_CYCLE_PHASE_REP8_WARMUP_SET1_INTENSITY = 0.5
const val REALIZATION_CYCLE_PHASE_REP8_WARMUP_SET1_REPETITIONS = 5
const val REALIZATION_CYCLE_PHASE_REP8_WARMUP_SET2_INTENSITY = 0.6
const val REALIZATION_CYCLE_PHASE_REP8_WARMUP_SET2_REPETITIONS = 3
const val REALIZATION_CYCLE_PHASE_REP8_WARMUP_SET3_INTENSITY = 0.7
const val REALIZATION_CYCLE_PHASE_REP8_WARMUP_SET3_REPETITIONS = 2
const val REALIZATION_CYCLE_PHASE_REP8_WARMUP_SET4_INTENSITY = 0.75
const val REALIZATION_CYCLE_PHASE_REP8_WARMUP_SET4_REPETITIONS = 1
const val REALIZATION_CYCLE_PHASE_REP8_MAIN_SET_INTENSITY = 0.8
const val REALIZATION_CYCLE_PHASE_REP8_MAIN_SET_REPETITIONS_CRITERION = 8

const val REALIZATION_CYCLE_PHASE_REP5_WARMUP_SET1_INTENSITY = 0.5
const val REALIZATION_CYCLE_PHASE_REP5_WARMUP_SET1_REPETITIONS = 5
const val REALIZATION_CYCLE_PHASE_REP5_WARMUP_SET2_INTENSITY = 0.6
const val REALIZATION_CYCLE_PHASE_REP5_WARMUP_SET2_REPETITIONS = 3
const val REALIZATION_CYCLE_PHASE_REP5_WARMUP_SET3_INTENSITY = 0.7
const val REALIZATION_CYCLE_PHASE_REP5_WARMUP_SET3_REPETITIONS = 2
const val REALIZATION_CYCLE_PHASE_REP5_WARMUP_SET4_INTENSITY = 0.75
const val REALIZATION_CYCLE_PHASE_REP5_WARMUP_SET4_REPETITIONS = 1
const val REALIZATION_CYCLE_PHASE_REP5_WARMUP_SET5_INTENSITY = 0.8
const val REALIZATION_CYCLE_PHASE_REP5_WARMUP_SET5_REPETITIONS = 1
const val REALIZATION_CYCLE_PHASE_REP5_MAIN_SET_INTENSITY = 0.85
const val REALIZATION_CYCLE_PHASE_REP5_MAIN_SET_REPETITIONS_CRITERION = 5

const val REALIZATION_CYCLE_PHASE_REP3_WARMUP_SET1_INTENSITY = 0.5
const val REALIZATION_CYCLE_PHASE_REP3_WARMUP_SET1_REPETITIONS = 5
const val REALIZATION_CYCLE_PHASE_REP3_WARMUP_SET2_INTENSITY = 0.6
const val REALIZATION_CYCLE_PHASE_REP3_WARMUP_SET2_REPETITIONS = 3
const val REALIZATION_CYCLE_PHASE_REP3_WARMUP_SET3_INTENSITY = 0.7
const val REALIZATION_CYCLE_PHASE_REP3_WARMUP_SET3_REPETITIONS = 2
const val REALIZATION_CYCLE_PHASE_REP3_WARMUP_SET4_INTENSITY = 0.75
const val REALIZATION_CYCLE_PHASE_REP3_WARMUP_SET4_REPETITIONS = 1
const val REALIZATION_CYCLE_PHASE_REP3_WARMUP_SET5_INTENSITY = 0.8
const val REALIZATION_CYCLE_PHASE_REP3_WARMUP_SET5_REPETITIONS = 1
const val REALIZATION_CYCLE_PHASE_REP3_WARMUP_SET6_INTENSITY = 0.85
const val REALIZATION_CYCLE_PHASE_REP3_WARMUP_SET6_REPETITIONS = 1
const val REALIZATION_CYCLE_PHASE_REP3_MAIN_SET_INTENSITY = 0.9
const val REALIZATION_CYCLE_PHASE_REP3_MAIN_SET_REPETITIONS_CRITERION = 3



