package kr.valor.juggernaut.common

const val PHASE_REP10_WARMUP_COUNT = 4
const val PHASE_REP8_WARMUP_COUNT = 4
const val PHASE_REP5_WARMUP_COUNT = 5
const val PHASE_REP3_WARMUP_COUNT = 6

const val ACCUMULATION_CYCLE_PHASE_REP10_INTENSITY = 0.6
const val ACCUMULATION_CYCLE_PHASE_REP10_REPETITIONS = 10
const val ACCUMULATION_CYCLE_PHASE_REP10_SETS = 4

const val ACCUMULATION_CYCLE_PHASE_REP8_INTENSITY = 0.65
const val ACCUMULATION_CYCLE_PHASE_REP8_REPETITIONS = 8
const val ACCUMULATION_CYCLE_PHASE_REP8_SETS = 4

const val ACCUMULATION_CYCLE_PHASE_REP5_INTENSITY = 0.7
const val ACCUMULATION_CYCLE_PHASE_REP5_REPETITIONS = 5
const val ACCUMULATION_CYCLE_PHASE_REP5_SETS = 5

const val ACCUMULATION_CYCLE_PHASE_REP3_INTENSITY = 0.75
const val ACCUMULATION_CYCLE_PHASE_REP3_REPETITIONS = 3
const val ACCUMULATION_CYCLE_PHASE_REP3_SETS = 6